name: Suying666-auto-clock-in
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      my_input:
        description: 'input'
        required: true
jobs:
  build:
    name: Suying666-clock-in by GitHub Actions
    runs-on: ubuntu-20.04

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v3

      - name: 2. setup python3...
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: 3. do sign in...
        run: python index.py "$EMAIL" "$PASSWD" "$KEY"
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          KEY: ${{ secrets.KEY }}
